<#
.SYNOPSIS
    Get-CertUtilCache - Collect certutil URLcache artifacts from INetCache

.DESCRIPTION
    Enumerates the Windows INetCache directory for files dropped by certutil's
    -urlcache flag. Also checks common attacker staging paths for files that
    match the download pattern generated by the emulation script.

    CertUtil always writes to INetCache regardless of the output path specified
    in the command - this is a reliable forensic artifact even when attackers
    try to redirect output to another location.

.NOTES
    Read-only. Run as Administrator for full access to all user caches.
#>

[CmdletBinding()]
param(
    [DateTime]$StartTime    = (Get-Date).AddHours(-24),
    [string]  $OutputPath   = "C:\TriageOutput",
    [string]  $ProfileUser  = $env:USERNAME
)

$findings = [System.Collections.Generic.List[string]]::new()
$results  = @()

function Add-Finding { param($msg, $sev="INFO") $findings.Add("[$sev] $msg") }

$userProfile = if ($ProfileUser -eq $env:USERNAME) {
    $env:USERPROFILE
} else {
    "C:\Users\$ProfileUser"
}

# -- INetCache -----------------------------------------------------------------
$inetCachePaths = @(
    "$userProfile\AppData\Local\Microsoft\Windows\INetCache",
    "$userProfile\AppData\Local\Microsoft\Windows\WebCache"
)

foreach ($cachePath in $inetCachePaths) {
    if (-not (Test-Path $cachePath)) { continue }

    Add-Finding "Scanning: $cachePath"
    $cacheFiles = Get-ChildItem $cachePath -Recurse -File -ErrorAction SilentlyContinue |
                  Where-Object { $_.LastWriteTime -ge $StartTime } |
                  Sort-Object LastWriteTime -Descending

    Add-Finding "INetCache - $($cacheFiles.Count) files modified in window"

    foreach ($f in $cacheFiles) {
        $sev = switch -Regex ($f.Extension) {
            "\.exe|\.dll|\.ps1|\.bat|\.vbs|\.msi" { "HIGH" }
            "\.zip|\.rar|\.7z|\.gz"               { "MEDIUM" }
            default                                { "LOW" }
        }
        Add-Finding "CACHE FILE: $($f.FullName) [$($f.Length) bytes] LastWrite: $($f.LastWriteTime)" -sev $sev
        $results += [PSCustomObject]@{
            Path      = $f.FullName
            SizeBytes = $f.Length
            Extension = $f.Extension
            LastWrite = $f.LastWriteTime.ToString("o")
            Severity  = $sev
        }
    }
}

# -- Attacker staging paths (certutil output redirection targets) --------------
$stagingPaths = @(
    "C:\Windows\Temp",
    "C:\ProgramData",
    "$userProfile\AppData\Local\Temp",
    "$userProfile\Downloads"
)

Add-Finding "Checking common certutil output staging paths..."
foreach ($stage in $stagingPaths) {
    if (-not (Test-Path $stage)) { continue }
    $stageFiles = Get-ChildItem $stage -File -ErrorAction SilentlyContinue |
                  Where-Object { $_.LastWriteTime -ge $StartTime }
    if ($stageFiles) {
        Add-Finding "STAGING PATH $stage - $($stageFiles.Count) new files" -sev "MEDIUM"
        foreach ($f in $stageFiles) {
            Add-Finding "  FILE: $($f.Name) [$($f.Length) bytes] $($f.LastWriteTime)" -sev "MEDIUM"
            $results += [PSCustomObject]@{
                Path      = $f.FullName
                SizeBytes = $f.Length
                Extension = $f.Extension
                LastWrite = $f.LastWriteTime.ToString("o")
                Severity  = "MEDIUM"
            }
        }
    }
}

# -- Write JSON ----------------------------------------------------------------
$jsonPath = "$OutputPath\certutil_cache.json"
$results | ConvertTo-Json -Depth 5 | Out-File -FilePath $jsonPath -Encoding UTF8
Add-Finding "CertUtil cache results saved: $jsonPath - Total artifacts: $($results.Count)"
return $findings
